### PR TITLE
lb_sims basic

### PR DESCRIPTION
**Pull request by antolonappan**
A basic repo structure for litebird simulation which includes. simulation, component separation, lensing reconstruction and delensing.

### CODE REVIEW

**Review by zonca — COMMENTED** [review]
Please add a README.md that explain what is the purpose of this package and how it should be used, and who is expected to run it.

**Comment by antolonappan** [comment]
@zonca  Thanks for the comment, I have added a basic Readme. This will be updated as we will update the scripts

**Comment by zonca** [comment]
@antolonappan is this package supposed to be maintained and developed long-term or it is just for the CMB-S4xLiteBIRD work?

**Comment by antolonappan** [comment]
@zonca My idea is for S4xLiteBIRD works, there can be also a 's4_sims' for the s4 side simulation, if they gonna contribute. Also we could maintain it for the future updates. 

If we want to start another repo for the analysis exclusively, we can do that as well.

**Comment by zonca** [comment]
@antolonappan S4 has already a pipeline maintained by the lowell BB group, so I don't think they will be contributing.
I think it would be better to have this package in a separate repository, especially if you plan to maintain it in the future.
Then when you execute an analysis run, it would be good to document the configuration files that you used for that specific run in the `litebird/litebirdXS4` repository.

**Comment by antolonappan** [comment]
@zonca sounds good!

**Pull request closed without merging**
