### PR TITLE
Extract instrument model to file

### PR DESCRIPTION
**Pull request by zonca**
- added private repo as submodule
- Repository title

### CODE REVIEW

**Comment by zonca** [comment]
@giuspugl can you review this one if needed (mostly the notebook) together with https://github.com/litebird/litebirdXS4-private/pull/2?

**Comment by zonca** [comment]
the notebook reads the JSON and writes to the format expected by `mapsims`

**Comment by giuspugl** [comment]
> @giuspugl can you review this one

sure can you assign me as reviewer ?

**Comment by zonca** [comment]
@giuspugl I don't have permissions to merge, can you please review and merge?

**Review by giuspugl — COMMENTED** [review]
all good !

**Pull request merged**
