### PR TITLE
Cmb signals

### PR DESCRIPTION
**Pull request by carronj**
Module that build the s4 and lb maps from the lensed CMBs that were previously stored on disk.

### CODE REVIEW

**Comment by carronj** [comment]
The relevant methods are get_s4_map and get_lb_map in maps.py.

**Comment by antolonappan** [comment]
Hi @carronj, I think this repo mainly has the config files for the analysis.  
I have made a repo https://github.com/litebird/LBxS4 for the simulation, lensing, delensing and likelihood works. Maybe we can import your script there. 

@zonca Please correct me If I am wrong.

**Comment by zonca** [comment]
@antolonappan, this is just a script combining maps, I think it is fine here.

@carronj can you add a README.md with details on what this does and how to use it?

**Comment by zonca** [comment]
@carronj can you add a README.md with details on what this does and how to use it?

**Comment by carronj** [comment]
I have added a readme pointing to a notebook

**Comment by zonca** [comment]
@carronj I am trying to execute the notebook,
`plancklens` is not on PyPI, I installed from https://github.com/carronj/plancklens
however I get:

    FileNotFoundError: /global/common/software/cmb/zonca/conda/s4xlb/lib/python3.10/site-packages/plancklens/data/cls/FFP10_wtensors_tensCls.dat not found.

**Comment by carronj** [comment]
Hi Andrea,

plancklens should usually be installed in the editable way 

But there is nothing there really that depends on plancklens. If that fine with you I can simply add the files with the CAMB input spectra in the litebirdXS4 repo ?

**Comment by zonca** [comment]
yes, please, adding the files and updating the notebook is fine

**Comment by carronj** [comment]
The loading the maps demo is now in maps.ipynb

**Comment by zonca** [comment]
thanks @carronj, I've added `s4mapsims` as a submodule so that we have easier access to the instrument model

**Pull request merged**
